
import { GoogleGenAI, Modality } from "@google/genai";
import { QuizSession, QuizStatus, Submission, SubmissionType } from '../types';
import { QuizService } from './mockBackend';

export const API = {
  fetchSession: async (id: string): Promise<QuizSession> => {
    return QuizService.getSession();
  },

  updateSessionStatus: async (status: QuizStatus): Promise<QuizSession> => {
    return QuizService.updateStatus(status);
  },

  setCurrentQuestion: async (questionId: string): Promise<QuizSession> => {
    return QuizService.setQuestion(questionId);
  },

  submitTeamAnswer: async (teamId: string, questionId: string, answer?: number, type: SubmissionType = 'ANSWER'): Promise<Submission> => {
    return QuizService.submitAnswer(teamId, questionId, answer, type);
  },

  revealAnswerAndProcessScores: async (): Promise<QuizSession> => {
    return QuizService.revealAndScore();
  },

  resetSession: async (): Promise<QuizSession> => {
    return QuizService.resetSession();
  },

  forcePass: async (): Promise<QuizSession> => {
    return QuizService.forcePass();
  },

  getAIHostInsight: async (status: QuizStatus, questionText?: string, context?: string): Promise<string> => {
    try {
      const genAI = new GoogleGenAI({ apiKey: process.env.API_KEY });
      const model = 'gemini-3-flash-preview';
      
      // Prompt engineering for specific persona: "Cool lady, natural Indian English, good vocabulary"
      const prompt = `
        You are 'Aura', a sophisticated, intelligent, and cool AI quiz host with a natural Indian English speaking style.
        You use polished vocabulary (e.g., "splendid", "precisely", "alas", "commendable").
        
        Current Situation:
        - Quiz Status: ${status}
        ${questionText ? `- Question: "${questionText}"` : ''}
        ${context ? `- Update: ${context}` : ''}

        Instructions:
        1. Keep it brief (max 15 words).
        2. Be encouraging but competitive.
        3. If status is LIVE, encourage teams to answer.
        4. If status is REVEALED, comment on the result (correct/wrong) with wit.
        5. Return ONLY the spoken text, no quotes.
      `;

      const response = await genAI.models.generateContent({
        model: model,
        contents: prompt
      });

      return response.text || "Processing data streams...";
    } catch (error) {
      console.error("Gemini Error:", error);
      return "Systems operational.";
    }
  },

  generateAuraAudio: async (text: string): Promise<string | undefined> => {
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
      // Using 'Kore' as it is the standard female voice option. 
      // The "Indian English" feel comes from the text vocabulary and structure generated by the LLM.
      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-preview-tts",
        contents: [{ parts: [{ text: text }] }],
        config: {
          responseModalities: [Modality.AUDIO],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: 'Kore' },
            },
          },
        },
      });
      return response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    } catch (error) {
      console.error("TTS Error:", error);
      return undefined;
    }
  }
};
